### ISSUE TITLE
Image refs not replaced in collapsable sections

### ISSUE THREAD

**Issue by Roymprog** [binxio/wordpress-markdown-blog-loader#5]
In my blog I created a collapsible section with an image in it and noticed the image references don't get replaced correctly.

### Example input Markdown:
```md
<details>

<summary>Some summary</summary>

![Image high level design](./images/banner.jpg)

</details>
``` 

### Expected output:
```md
<details>

<summary>Some summary</summary>

<p><img decoding="async" alt="Image high level design" src="https://xebia.com/wp-content/uploads/2023/08/my-fancy-blog-banner.jpg" /></p>
</details>

```

### Actual output:
```md
<details>

<summary>Some summary</summary>

<p>![Image high level design](https://xebia.com/wp-content/uploads/2023/08/my-fancy-blog-banner.jpg)</p>

</details>

```

**Comment by Roymprog** [comment]
I guess this is more a feature than a bug. The [python markdown writer](https://python-markdown.github.io/#goals) doesn't support the syntax

**Comment by mvanholsteijn** [comment]
It should work. Do you have a newline between the ] and the ( ?

**Comment by mvanholsteijn** [comment]
Or may be it is because you embedded markdown inside html?

**Comment by Roymprog** [comment]
> Or may be it is because you embedded markdown inside html?

This is it as far as I understand. The markdown writer [ignores everything within the html tags](https://daringfireball.net/projects/markdown/syntax#html).

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block

**Comment by mvanholsteijn** [comment]
Fair enough. 😃
