### ISSUE TITLE
Is it possible to specify tags?

### ISSUE THREAD

**Issue by Kamilcuk** [binxio/wordpress-markdown-blog-loader#7]
Hi, absolutely an amazing project. I see it is possible to specify category. Is it possible to specify tags associated with the post? Thanks!

**Comment by mvanholsteijn** [comment]
Yes. just specify a list of categories in the frontmatter header.

```
categories:
  - aws
  - cloud
```

you need to specify an existing category:  you cannot add new categories.

**Comment by Kamilcuk** [comment]
Hi, that's category. A tag of a post is something separate. From the wordpress web UI:
![obraz](https://github.com/binxio/wordpress-markdown-blog-loader/assets/15679217/88c50dd3-6e6f-4f59-a676-c5c6485ce1a0)
